name: Primer Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  verificar-html:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Verificar que existe index.html
        run: test -f index.html

      - name: Verificar estructura HTML básica
        run: |
          grep -q "<html>" index.html
          grep -q "<body>" index.html
          grep -q "</html>" index.html

      - name: Verificar titulo de la pagina
        run: grep -q "<title>Desarrollo Seguro</title>" index.html

      - name: Mostrar mensaje final
        run: echo "El pipeline CI se ejecutó correctamente"